proxy:
  image: cpuguy83/docker-grand-ambassador
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name demo_phpfpm_1 -name demo_redis0cache_1"


nginx:
  build: conf/nginx
  volumes:
    - conf/nginx/config:/etc/nginx
  links:
    - "proxy:phpfpm"
  volumes_from:
    - phpfpm
  ports:
    - "80:80"
    - "443:443"

phpfpm:
  build: conf/phpfpm
  volumes:
    - conf/phpfpm/config:/usr/local/etc
    - src:/var/www/html
  links:
    - "proxy:redis0cache"

redis0cache:
  build: conf/redis
  volumes:
    - conf/redis/config:/usr/local/etc/redis
    - data/redis:/data
  ports:
   - "6379:6379"
