nginx:
  build: conf/nginx
  volumes:
    - conf/nginx/config:/etc/nginx
  links:
    - phpfpm
  volumes_from:
    - phpfpm
  ports:
    - "80:80"
    - "443:443"

phpfpm:
  build: conf/phpfpm
  links:
    - redis0cache
  volumes:
    - conf/phpfpm/config:/usr/local/etc
    - src:/var/www/html

redis0cache:
  build: conf/redis
  volumes:
    - conf/redis/config:/usr/local/etc/redis
    - data/redis:/data
  ports:
   - "6379:6379"
