version: '2'

services:
  varnish:
    image: windperson/docker-varnish-cache
    env_file:
      - ./conf/varnish-cache/env/web.env
    volumes:
      - ./conf/varnish-cache/vcl:/etc/varnish/
    links:
      - default_site:normal_site
    ports:
      - "80:80"
    networks:
      - back_end

  # application container
  default_site:
    build: conf/nginx
    volumes:
      - ./conf/nginx/config:/etc/nginx
    links:
      - phpfpm
    volumes_from:
      - phpfpm
    networks:
      - back_end

  phpfpm:
    build: conf/phpfpm
    volumes:
      - ./conf/phpfpm/config:/usr/local/etc
      - ./src:/var/www/html
    links:
      - redis0cache
    networks:
      - back_end

  #cache container
  redis0cache:
    build: conf/redis
    volumes:
      - ./conf/redis/config:/usr/local/etc/redis
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - back_end

networks:
  back_end:
