version: '2'

services:
  web:
    build: conf/nginx
    links:
      - phpfpm
    volumes:
      - ./conf/nginx/config:/etc/nginx
    volumes_from:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"

  phpfpm:
    build: conf/phpfpm
    volumes:
      - ./conf/phpfpm/config:/usr/local/etc
      - ./src:/var/www/html
