FROM busybox
MAINTAINER windperson
RUN mkdir -p /usr/local/etc/redis
COPY ./config /usr/local/etc/redis
VOLUME /usr/local/etc/redis
CMD echo "this container should exit with code 0 immediately"
